import numpy as np

MAX_THRUST = 10

INITIAL_POSITION = [
    200.0,
    100.0
]
INITIAL_THETA = np.radians(-45)
INITIAL_VELOCITY = 10 * np.array([
    np.cos(INITIAL_THETA + 1.5 * np.pi),
    np.sin(INITIAL_THETA + 1.5 * np.pi)
])

TIMESTEP = 0.2
PLANNER_N_HORIZON = 50
TRACKER_N_HORIZON = 10


ANIMATION_SIZE = (1920, 1080)
ANIMATION_SIZE = (1800, 900)
DRAGON_IMG_WIDTH, DRAGON_IMG_HEIGHT = 326, 326
FLAME_IMG_WIDTH, FLAME_IMG_HEIGHT = 54, 137
ANIMATION_SCALE = 1 / 2

X0 = INITIAL_POSITION + [INITIAL_THETA] + INITIAL_VELOCITY.tolist() + [0]

DRAGON_PIXEL_HEIGHT = 243
DRAGON_PIXEL_WIDTH = 200
DRAGON_PIXEL_CG_HEIGHT = 80
DRAGON_PIXEL_THRUST_ARM = 75
DRAGON_PIXEL_CG_HEIGHT_OFFSET = DRAGON_IMG_HEIGHT / 2

DRAGON_MASS = 1
DRAGON_WIDTH = 10
DRAGON_HEIGHT = DRAGON_WIDTH / DRAGON_PIXEL_WIDTH * DRAGON_PIXEL_HEIGHT
DRAGON_CG_HEIGHT = DRAGON_WIDTH / DRAGON_PIXEL_WIDTH * DRAGON_PIXEL_CG_HEIGHT
DRAGON_THRUST_ARM = DRAGON_WIDTH / DRAGON_PIXEL_WIDTH * DRAGON_PIXEL_THRUST_ARM
DRAGON_I = DRAGON_MASS * (3 * DRAGON_WIDTH ** 2 + 4 * DRAGON_HEIGHT ** 2) / 72

G = 9.80665
